### ISSUE TITLE
Remaining time is not preserved on "switchCountdown" when "leftTime" is used.

### ISSUE THREAD

**Issue by mc-mosa** [mlinquan/vue-awesome-countdown#12] opened 2019-05-26 14:48 UTC
I am using this library on a project and I noticed that calling the `stopCountdown()` method stops the countdown. When I start the countdown again, the time passed is taken into account

This is observable also in the demo page https://vac.js.org/examples/methods/all-methods.html. 
Just click on `stop`, wait for some time, and click `start` again.

I could just not render the component as a work around, e.g. `v-if="isCounting"` instead of using the `stopCountdown()` method

_Originally posted by @bi6o in https://github.com/mlinquan/vue-awesome-countdown/issues/8#issuecomment-491050477_

**Comment by mlinquan** [comment] 2019-05-28 06:28
@mc-mosa I think this problem can be solved by adding a pause method.
Do you have any good suggestions?

**Comment by mlinquan** [comment] 2019-05-28 07:39
Thank you for your rp.
The issue was fixed in version 1.0.14.

**Comment by mc-mosa** [comment] 2019-05-28 08:36
I think line number 133 in `src/vue-awesome-countdown.vue` is causing the same issue, it should be

```
vm.remainingTime = new Date(vm.actualEndTime).getTime() - new Date().getTime()
```

what do you think?

**Comment by mlinquan** [comment] 2019-05-28 10:55
> I think line number 133 in `src/vue-awesome-countdown.vue` is causing the same issue, it should be
> 
> ```js
> vm.remainingTime = new Date(vm.actualEndTime).getTime() - new Date().getTime()
> ```
> 
> what do you think?

I think both methods can be used.
Your code is more concise.
I may use your method in the next version.
Thanks again.

**Comment by mc-mosa** [comment] 2019-05-28 11:24
Your method doesn't take into account that the timer might be **paused** (i.e. stopped then started again after some time), because you're calculating the `remainingTime` based on the `actualStartTime`  which never changes (once the timer has **_restarted_**), unlike the `actualEndTime` which is changed everytime the timer is started/resumed.. and that's the subject of this issue; to handle the pause feature.

**Comment by bi6o** [comment] 2019-05-28 13:38
I can confirm that the issue is not resolved in the new version, and again it is observable only in the test page that you provide  https://vac.js.org/examples/methods/all-methods.html.

**Comment by mlinquan** [comment] 2019-10-24 08:31
Pause is added in the new version. You can try the new version 1.0.18.
`vac.pauseCountdown()`

**Closed** 2019-10-24 08:32 UTC
