### ISSUE TITLE
onStop event is not emitted

### ISSUE THREAD

**Issue by mc-mosa** [mlinquan/vue-awesome-countdown#8] opened 2019-04-29 21:15 UTC
The onStop event is not emitted when the countdown is stopped

**Comment by bi6o** [comment] 2019-05-09 20:17
I am using this library on a project and I noticed that calling the `stopCountdown()` method stops the countdown. When I start the countdown again, the time passed is taken into account

This is observable also in the demo page https://vac.js.org/examples/methods/all-methods.html. 
Just click on `stop`, wait for some time, and click `start` again.

I could just not render the component as a work around, e.g. `v-if="isCounting"`

Is the issue I mentioned related to this event not being emitted? And is it expected for the fix to be merged?

**Comment by mc-mosa** [comment] 2019-05-10 04:42
No this doesn't have anything to do with the problem you mentioned.

I have noticed it as well but don't have much time to look into it at the moment. I don't know if that's an intended behavior or just a bug. Will try to look into it as soon as I have the time.

**Comment by bi6o** [comment] 2019-05-10 07:07
Doesn't seem to me like an intended behavior. Thank you for that, I will keep my :eyes: open for this one

**Comment by mlinquan** [comment] 2019-05-20 07:17
Merged

**Comment by bi6o** [comment] 2019-05-20 08:31
Hey, I saw that you merged a fix this morning. I have updated the library and the bug is still happening, that's also true for the live example that I mentioned before https://vac.js.org/examples/methods/all-methods.html . Am I missing something?

**Comment by mc-mosa** [comment] 2019-05-22 22:31
Hey, sorry.. the merge was for the bug mentioned in the title of this issue. I haven't got the chance to look into the bug we discussed earlier, will try to do that this weekend.

**Comment by mlinquan** [comment] 2019-05-28 07:52
@bi6o @mc-mosa The issue was fixed in version 1.0.14.

**Closed** 2019-05-28 08:38 UTC
Labels: bug
